import { describe, it, expect } from 'vitest';
import { unwrapEnvelope } from './unwrapEnvelope.js';

describe('unwrapEnvelope', () => {
  it('returns null for null / undefined / empty / whitespace-only', () => {
    expect(unwrapEnvelope(null)).toBeNull();
    expect(unwrapEnvelope(undefined)).toBeNull();
    expect(unwrapEnvelope('')).toBeNull();
    expect(unwrapEnvelope('   \n  ')).toBeNull();
  });

  it('passes plain user text through unchanged (trimmed)', () => {
    expect(unwrapEnvelope('  fix the auth bug  ')).toBe('fix the auth bug');
  });

  it('unwraps the slash-command triple into "/name args"', () => {
    const raw = [
      '<command-message>loop</command-message>',
      '<command-name>/loop</command-name>',
      '<command-args>work through research/ui-content-issues.md</command-args>',
    ].join('\n');
    expect(unwrapEnvelope(raw)).toBe(
      '/loop work through research/ui-content-issues.md',
    );
  });

  it('renders "/name" alone when command-args is missing', () => {
    const raw = [
      '<command-message>review</command-message>',
      '<command-name>/review</command-name>',
    ].join('\n');
    expect(unwrapEnvelope(raw)).toBe('/review');
  });

  it('normalizes a command-name that does not already start with a slash', () => {
    const raw = '<command-name>review</command-name>';
    expect(unwrapEnvelope(raw)).toBe('/review');
  });

  it('unwraps scheduled-task envelopes into "↻ scheduled-task: <name>"', () => {
    const raw =
      '<scheduled-task name="nightly-rescan" cron="0 0 * * *">payload</scheduled-task>';
    expect(unwrapEnvelope(raw)).toBe('↻ scheduled-task: nightly-rescan');
  });

  it('preserves user prose that follows a slash-command triple', () => {
    const raw = [
      '<command-name>/loop</command-name>',
      '<command-args>fix the bug</command-args>',
      '',
      'extra context the user added',
    ].join('\n');
    expect(unwrapEnvelope(raw)).toContain('/loop fix the bug');
    expect(unwrapEnvelope(raw)).toContain('extra context the user added');
  });

  it('drops a <system-reminder> block and returns null when nothing else remains', () => {
    const raw = [
      '<system-reminder>',
      'You have new permissions enabled. Use them wisely.',
      '</system-reminder>',
    ].join('\n');
    expect(unwrapEnvelope(raw)).toBeNull();
  });

  it('drops a <system-reminder> block and keeps the user content after it', () => {
    const raw = [
      '<system-reminder>',
      'Tool list updated.',
      '</system-reminder>',
      '',
      'actual user message',
    ].join('\n');
    expect(unwrapEnvelope(raw)).toBe('actual user message');
  });

  it('drops <task-notification> blocks', () => {
    const raw = [
      '<task-notification>',
      'Subagent reported back: 3 findings.',
      '</task-notification>',
      'now what?',
    ].join('\n');
    expect(unwrapEnvelope(raw)).toBe('now what?');
  });

  it('drops <local-command-stdout> and <local-command-stderr> blocks', () => {
    const raw = [
      '<local-command-stdout>npm install OK</local-command-stdout>',
      '<local-command-stderr>warning: deprecated</local-command-stderr>',
      'continue please',
    ].join('\n');
    expect(unwrapEnvelope(raw)).toBe('continue please');
  });

  it('drops literal-prefix wrappers (no XML tags)', () => {
    const raw = [
      'Caveat: The messages below were generated by AI.',
      'real user input here',
    ].join('\n');
    expect(unwrapEnvelope(raw)).toBe('real user input here');
  });

  it('drops "[Request interrupted by user" wrapper', () => {
    expect(
      unwrapEnvelope('[Request interrupted by user with text: stop]'),
    ).toBeNull();
  });

  it('drops "Base directory for this skill:" wrapper', () => {
    const raw =
      'Base directory for this skill: /home/u/.claude/skills/foo\n\nthen the real prompt';
    expect(unwrapEnvelope(raw)).toBe('then the real prompt');
  });

  it('drops "This session is being continued" preamble', () => {
    const raw = [
      'This session is being continued from a previous conversation that ran out of context.',
      '',
      'resume what we were doing',
    ].join('\n');
    expect(unwrapEnvelope(raw)).toBe('resume what we were doing');
  });

  it('returns null when only wrappers and no payload survive', () => {
    const raw = [
      '<command-message>loop</command-message>',
      '<command-name></command-name>',
      '<command-args></command-args>',
    ].join('\n');
    // Empty name → unwraps to "/" which is technically still meaningful
    // synthesis. We accept either "/" or null as long as it is not the
    // raw envelope.
    const got = unwrapEnvelope(raw);
    expect(got).not.toMatch(/<command-/);
  });

  it('does not blow up on unbalanced tags', () => {
    expect(() => unwrapEnvelope('<system-reminder>oops no close')).not.toThrow();
  });

  it('leaves real "<" characters in user prose alone', () => {
    expect(unwrapEnvelope('compare 3 < 5 in the answer')).toBe(
      'compare 3 < 5 in the answer',
    );
  });
});
