/**
 * Phase Rev3-F F9 — curator feed top section for the PRACTICE
 * surface.
 *
 * Renders the top-K items the curator ranked, with kind chip +
 * title + composite score + falsifier-status tag. If F8's meta-
 * accuracy kernel flagged drift, the section gets a banner row at
 * the top.
 *
 * When the feed file is absent (no /curate run yet), renders an
 * empty-state row explaining the curator hasn't run. The /curate
 * skill scaffold (F1+F2) is in place; full pipeline ships when
 * F3+F4 kernels + skill orchestration wire together — until then
 * this surface is "scaffold renders the empty state."
 */
import { useEffect, useState } from 'react';

import {
  loadCuratorFeed,
  type CuratorFeedFile,
  type CuratorFeedItem,
  type CuratorItemKind,
  type CuratorFalsifierStatus,
} from '../data/curatorFeedClient.js';
import { stripMarkdown } from '../util/stripMarkdown.js';

const KIND_LABEL: Record<CuratorItemKind, string> = {
  narrative: 'NARRATIVE',
  'knowledge-debt': 'KNOWLEDGE DEBT',
  'applied-pattern': 'APPLIED PATTERN',
};

const FALSIFIER_TAG_LABEL: Record<CuratorFalsifierStatus, string> = {
  verified: 'VERIFIED',
  'skipped-by-user': 'SKIPPED',
  unavailable: 'UNVERIFIED',
};

/**
 * Scaffold gate (issue #120). The curator ranker (F3), falsifier verifier
 * (F4), and meta-validation (F8) kernels are NOT yet wired into any
 * production path, and the MCP server has no transport — so any
 * `falsifierStatus` tag on a feed item is a PLACEHOLDER, not a real
 * verdict. While this is `false` the UI must not present "VERIFIED" as an
 * affirmative "passed the falsifier" claim, and it shows a standing
 * scaffold disclaimer so a reader can't mistake a placeholder for a
 * verified finding.
 *
 * FLIP-GUARDRAIL — do NOT set this to `true` until per-item verdict
 * provenance actually exists: F4 must write a real per-finding verdict
 * AND `curator-feed.json` must carry a provenance field the UI can trust.
 * A coarse global flip WITHOUT that provenance would re-introduce blanket
 * "VERIFIED" for items that never passed a real falsifier — the exact
 * trust bug #120 names. Gate the flip on the provenance landing, not on
 * the kernels merely existing.
 */
export const CURATOR_PIPELINE_LIVE = false;

export interface CuratorFeedProps {
  /** Base URL for the chat-arch-data sidecar tree. */
  dataDirBaseUrl?: string;
}

/**
 * Loads the feed once on mount. The feed file is regenerated by the
 * /curate skill on user-triggered runs (manual or scheduled);
 * re-mounting refreshes.
 */
export function CuratorFeed({
  dataDirBaseUrl = 'chat-arch-data',
}: CuratorFeedProps): JSX.Element {
  const [feed, setFeed] = useState<CuratorFeedFile | null>(null);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    let cancelled = false;
    void loadCuratorFeed(dataDirBaseUrl).then((file) => {
      if (cancelled) return;
      setFeed(file);
      setLoaded(true);
    });
    return () => {
      cancelled = true;
    };
  }, [dataDirBaseUrl]);

  return (
    <section
      className="lcars-curator-feed"
      aria-labelledby="lcars-curator-feed-h"
    >
      <header className="lcars-curator-feed__header">
        <h3 id="lcars-curator-feed-h" className="lcars-curator-feed__title">WHAT TO LOOK AT NOW</h3>
        <p className="lcars-curator-feed__lead">
          Top items the curator surfaced this run. Ranking is deterministic
          (tier &gt; confidence &gt; recency &gt; correlation tie-break) —
          not a model judgement.
          {CURATOR_PIPELINE_LIVE ? (
            <>
              {' '}
              Items tagged{' '}
              <span className="lcars-curator-feed__falsifier-inline lcars-curator-feed__falsifier-inline--verified">
                VERIFIED
              </span>{' '}
              passed the falsifier; others carry their citation-hygiene tag for
              audit.
            </>
          ) : null}
        </p>
      </header>
      {!CURATOR_PIPELINE_LIVE && (
        <p
          className="lcars-curator-feed__scaffold-note"
          role="note"
          data-testid="curator-scaffold-note"
        >
          The curator ranker and falsifier are a scaffold — not yet wired into a
          production path. Any status tags shown below (VERIFIED / UNVERIFIED)
          are placeholders, not real verdicts.
        </p>
      )}
      {feed?.metaAccuracy?.inDrift === true && (
        <p
          className="lcars-curator-feed__drift-banner"
          role="status"
        >
          <span aria-hidden="true">⚠ </span>FALSIFIER DRIFT — accuracy lower bound{' '}
          {(feed.metaAccuracy.lowerBound * 100).toFixed(1)}% &lt; floor{' '}
          {(feed.metaAccuracy.floor * 100).toFixed(0)}% (n={feed.metaAccuracy.n}
          ). Re-calibrate before trusting verdicts.
        </p>
      )}
      {!loaded && (
        <p className="lcars-curator-feed__loading">Loading feed…</p>
      )}
      {loaded && feed === null && (
        <p className="lcars-curator-feed__empty">
          No curator feed yet. The <code>/curate</code> skill will populate
          this section on its next run.
        </p>
      )}
      {loaded && feed !== null && feed.items.length === 0 && (
        <p className="lcars-curator-feed__empty">
          Curator ran but had no items to surface. Wait for more evidence
          to accumulate, or run <code>/curate</code> again after the next
          scan.
        </p>
      )}
      {loaded && feed !== null && feed.items.length > 0 && (
        <ol className="lcars-curator-feed__list" role="list">
          {feed.items.map((item) => (
            <li key={`${item.kind}:${item.entityId}`} role="listitem">
              <CuratorFeedRow item={item} />
            </li>
          ))}
        </ol>
      )}
    </section>
  );
}

function CuratorFeedRow({ item }: { item: CuratorFeedItem }): JSX.Element {
  const titleId = `lcars-curator-feed-item-${item.kind}-${item.entityId}`;
  return (
    <article
      className="lcars-curator-feed__row"
      aria-labelledby={titleId}
    >
      <span className="lcars-curator-feed__rank">#{item.rank}</span>
      <span
        className={`lcars-curator-feed__kind lcars-curator-feed__kind--${item.kind}`}
      >
        {KIND_LABEL[item.kind]}
      </span>
      <span id={titleId} className="lcars-curator-feed__title-text">{stripMarkdown(item.title)}</span>
      <span
        className="lcars-curator-feed__composite"
        aria-label={`composite score ${item.compositeScore.toFixed(2)}`}
      >
        composite {item.compositeScore.toFixed(2)}
      </span>
      {item.tieBrokenByCorrelation === true && (
        <span
          className="lcars-curator-feed__tie-break"
          aria-label="rank decided by correlation tie-break"
        >
          tie-broken
        </span>
      )}
      {item.falsifierStatus !== undefined && (
        <span
          className={
            `lcars-curator-feed__falsifier lcars-curator-feed__falsifier--${item.falsifierStatus}` +
            (CURATOR_PIPELINE_LIVE ? '' : ' lcars-curator-feed__falsifier--placeholder')
          }
          aria-label={
            CURATOR_PIPELINE_LIVE
              ? `falsifier ${item.falsifierStatus}`
              : `falsifier ${item.falsifierStatus} (placeholder — pipeline is a scaffold)`
          }
          {...(CURATOR_PIPELINE_LIVE
            ? {}
            : { title: 'placeholder — the falsifier pipeline is a scaffold, not a real verdict' })}
        >
          {FALSIFIER_TAG_LABEL[item.falsifierStatus]}
          {CURATOR_PIPELINE_LIVE ? '' : ' (placeholder)'}
        </span>
      )}
      {item.reasoning !== undefined && item.reasoning.length > 0 && (
        <p className="lcars-curator-feed__reasoning">{stripMarkdown(item.reasoning)}</p>
      )}
    </article>
  );
}
