/**
 * Phase Rev3-F F9 — curator feed top section for the PRACTICE
 * surface.
 *
 * Renders the top-K items the curator ranked, with kind chip +
 * title + composite score + falsifier-status tag. If F8's meta-
 * accuracy kernel flagged drift, the section gets a banner row at
 * the top.
 *
 * When the feed file is absent (no /curate run yet), renders an
 * empty-state row explaining the curator hasn't run. The /curate
 * skill scaffold (F1+F2) is in place; full pipeline ships when
 * F3+F4 kernels + skill orchestration wire together — until then
 * this surface is "scaffold renders the empty state."
 */
import { useEffect, useState } from 'react';

import {
  loadCuratorFeed,
  type CuratorFeedFile,
  type CuratorFeedItem,
  type CuratorItemKind,
  type CuratorFalsifierStatus,
} from '../data/curatorFeedClient.js';

const KIND_LABEL: Record<CuratorItemKind, string> = {
  narrative: 'NARRATIVE',
  'knowledge-debt': 'KNOWLEDGE DEBT',
  'applied-pattern': 'APPLIED PATTERN',
};

const FALSIFIER_TAG_LABEL: Record<CuratorFalsifierStatus, string> = {
  verified: 'VERIFIED',
  'skipped-by-user': 'SKIPPED',
  unavailable: 'UNVERIFIED',
};

export interface CuratorFeedProps {
  /** Base URL for the chat-arch-data sidecar tree. */
  dataDirBaseUrl?: string;
}

/**
 * Loads the feed once on mount. The feed file is regenerated by the
 * /curate skill on user-triggered runs (manual or scheduled);
 * re-mounting refreshes.
 */
export function CuratorFeed({
  dataDirBaseUrl = 'chat-arch-data',
}: CuratorFeedProps): JSX.Element {
  const [feed, setFeed] = useState<CuratorFeedFile | null>(null);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    let cancelled = false;
    void loadCuratorFeed(dataDirBaseUrl).then((file) => {
      if (cancelled) return;
      setFeed(file);
      setLoaded(true);
    });
    return () => {
      cancelled = true;
    };
  }, [dataDirBaseUrl]);

  return (
    <section
      className="lcars-curator-feed"
      aria-label="curator feed — what to look at now"
    >
      <header className="lcars-curator-feed__header">
        <h3 className="lcars-curator-feed__title">WHAT TO LOOK AT NOW</h3>
        <p className="lcars-curator-feed__lead">
          Top items the curator surfaced this run. Ranking is deterministic
          (tier &gt; confidence &gt; recency &gt; correlation tie-break) —
          not a model judgement. Items tagged{' '}
          <span className="lcars-curator-feed__falsifier-inline lcars-curator-feed__falsifier-inline--verified">
            VERIFIED
          </span>{' '}
          passed the falsifier; others carry their citation-hygiene tag for
          audit.
        </p>
      </header>
      {feed?.metaAccuracy?.inDrift === true && (
        <p
          className="lcars-curator-feed__drift-banner"
          role="alert"
          aria-label="falsifier accuracy drift detected"
        >
          ⚠ FALSIFIER DRIFT — accuracy lower bound{' '}
          {(feed.metaAccuracy.lowerBound * 100).toFixed(1)}% &lt; floor{' '}
          {(feed.metaAccuracy.floor * 100).toFixed(0)}% (n={feed.metaAccuracy.n}
          ). Re-calibrate before trusting verdicts.
        </p>
      )}
      {!loaded && (
        <p className="lcars-curator-feed__loading">Loading feed…</p>
      )}
      {loaded && feed === null && (
        <p className="lcars-curator-feed__empty" role="status">
          No curator feed yet. The <code>/curate</code> skill will populate
          this section on its next run.
        </p>
      )}
      {loaded && feed !== null && feed.items.length === 0 && (
        <p className="lcars-curator-feed__empty" role="status">
          Curator ran but had no items to surface. Wait for more evidence
          to accumulate, or run <code>/curate</code> again after the next
          scan.
        </p>
      )}
      {loaded && feed !== null && feed.items.length > 0 && (
        <ol className="lcars-curator-feed__list" role="list">
          {feed.items.map((item) => (
            <li key={`${item.kind}:${item.entityId}`} role="listitem">
              <CuratorFeedRow item={item} />
            </li>
          ))}
        </ol>
      )}
    </section>
  );
}

function CuratorFeedRow({ item }: { item: CuratorFeedItem }): JSX.Element {
  return (
    <article
      className="lcars-curator-feed__row"
      aria-label={`${KIND_LABEL[item.kind]} — rank ${item.rank}`}
    >
      <span className="lcars-curator-feed__rank">#{item.rank}</span>
      <span
        className={`lcars-curator-feed__kind lcars-curator-feed__kind--${item.kind}`}
      >
        {KIND_LABEL[item.kind]}
      </span>
      <span className="lcars-curator-feed__title-text">{item.title}</span>
      <span
        className="lcars-curator-feed__composite"
        aria-label={`composite score ${item.compositeScore.toFixed(2)}`}
      >
        composite {item.compositeScore.toFixed(2)}
      </span>
      {item.tieBrokenByCorrelation === true && (
        <span
          className="lcars-curator-feed__tie-break"
          aria-label="rank decided by correlation tie-break"
        >
          tie-broken
        </span>
      )}
      {item.falsifierStatus !== undefined && (
        <span
          className={`lcars-curator-feed__falsifier lcars-curator-feed__falsifier--${item.falsifierStatus}`}
          aria-label={`falsifier ${item.falsifierStatus}`}
        >
          {FALSIFIER_TAG_LABEL[item.falsifierStatus]}
        </span>
      )}
      {item.reasoning !== undefined && item.reasoning.length > 0 && (
        <p className="lcars-curator-feed__reasoning">{item.reasoning}</p>
      )}
    </article>
  );
}
